name: Update backend

on:
  push:
    branches:
      - master

jobs:
  update_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update info
        shell: bash
        run: |
          chmod +x ./.github/scripts/check-markdown-update.sh && \
          ./.github/scripts/check-markdown-update.sh \
#          todo add prod url
          'scanner-dev.waves.tech' \ 
          ${{ secrets.LESSONS_SECRET_FOR_SYNC_PROD }}
